name: 'SourceCred Action'
description: 'Generate cred scores and an interface for your projects'
author: 'vsoch'
branding:
  icon: 'sliders'
  color: 'blue'
inputs:
  automated:
    description: >
      Push changes to the target branch.  If set to false (the default)
      open a pull request with changes instead.
    default: false
  branch-against:
    description: >
      If automated is set to false and we open a pull request, open the pull
      request against the branch specified here. This defaults to master.
    default: "master"
  project:
    description: >
      A GitHub project alias (e.g., @sourcecred), meaning an organization or
      full repository. This variable is only used if project-file (suggested)
      is not provided. 
    default: "@${{ github.repository }}"
    required: true
  project-file: 
    description: 'the path to a file containing a project config'
    required: true
  scores-json:
    description: 'the relative path to save the scores.json. Defaults to scores.json'
    default: "scores.json"
  target:
    description: 'an empty directory into which to build the site'
    required: false
  weights:
    description: 'path to a json file which contains a weights configuration.'
    default: null
    required: false
  token:
    description: >
      Auth token used to fetch the repository.
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SC_TARGET: ${{ inputs.target }}
    SC_PROJECT_FILE: ${{ inputs.project-file }}
    SC_PROJECT: ${{ inputs.project }}
    SC_AUTOMATED: ${{ inputs.automated }}
    SC_BRANCH_AGAINST: ${{ inputs.branch-against }}
    SC_SCORES_JSON: ${{ inputs.scores-json }}
    SC_WEIGHTS: ${{ inputs.weights }}
    SOURCECRED_GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_TOKEN: ${{ inputs.token }}
